server {
    listen 80;
    server_name static.local;
    
    # Intentional mistake: Missing X-Content-Type-Options
    
    location /assets {
        alias /var/www/assets;
        autoindex on;
    }
}
