user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    include       /etc/nginx/conf.d/*.conf;
    default_type  application/octet-stream;

    # LỖI 1: Không tắt server_tokens (Mặc định là on)
    # server_tokens off; 

    # LỖI 3 & 4: Thiếu hoàn toàn các Security Headers (X-Frame-Options, X-Content-Type-Options)

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }

    server {
        listen       443 ssl;
        server_name  localhost;

        ssl_certificate      /etc/ssl/mock_certs/nginx.crt;
        ssl_certificate_key  /etc/ssl/mock_certs/nginx.key;

        # LỖI 5: Sử dụng các giao thức TLS cũ, không an toàn
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        # LỖI 2: Thiếu header Strict-Transport-Security (HSTS)

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
}